"""
Pydantic schemas for the application.
"""

# Authentication schemas
from .auth import (
    UserLoginRequest,
    UserRegisterRequest,
    TokenRefreshRequest,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    ChangePasswordRequest,
    EmailVerificationRequest,
    ResendVerificationRequest,
    UserResponse,
    TokenResponse,
    TokenRefreshResponse,
    LoginResponse,
    RegisterResponse,
    RefreshResponse,
    LogoutResponse,
    ForgotPasswordResponse,
    ResetPasswordResponse,
    ChangePasswordResponse,
    EmailVerificationResponse,
    ResendVerificationResponse,
    SessionsResponse,
    RevokeSessionResponse,
    SessionInfo,
    ErrorResponse,
)

# User schemas
from .user import (
    UserCreateRequest,
    UserUpdateRequest,
    UserSkillRequest,
    UserQueryParams,
    UserResponse as UserDetailResponse,
    UserListResponse,
    UserSkillResponse,
    PaginationInfo,
    UserListResponseWrapper,
    UserResponseWrapper,
    UserCreateResponseWrapper,
    UserUpdateResponseWrapper,
    UserDeleteResponseWrapper,
    UserSkillResponseWrapper,
)

# Profile schemas
from .profile import (
    ProfileUpdateRequest,
    ProfileResponse,
    AvatarUploadResponse,
    ProfileUpdateResponse,
    ProfileResponseWrapper,
)

# Skills schemas
from .skills import (
    SkillRequest,
    SkillResponse,
    SkillListResponse,
    SkillCreateResponseWrapper,
    SkillUpdateResponseWrapper,
    SkillDeleteResponseWrapper,
)

# Project schemas
from .project import (
    ProjectCreateRequest,
    ProjectUpdateRequest,
    ProjectQueryParams,
    TeamMemberRequest,
    ProjectResponse,
    ProjectListResponse,
    TeamMemberResponse,
    ProjectCreateResponseWrapper,
    ProjectUpdateResponseWrapper,
    ProjectDeleteResponseWrapper,
    ProjectListResponseWrapper,
    ProjectResponseWrapper,
)

# Team schemas
from .team import (
    TeamMemberRoleUpdateRequest,
    TeamMemberDetailResponse,
    TeamListResponse,
    TeamMemberUpdateResponse,
    TeamMemberAddResponse,
    TeamMemberRemoveResponse,
    TeamStatsResponse,
    TeamStatsWrapper,
)

# Milestone schemas
from .milestone import (
    MilestoneCreateRequest,
    MilestoneUpdateRequest,
    MilestoneDependencyRequest,
    MilestoneResponse,
    MilestoneDetailResponse,
    MilestoneDependencyResponse,
    MilestoneListResponse,
    MilestoneCreateResponseWrapper,
    MilestoneUpdateResponseWrapper,
    MilestoneDeleteResponseWrapper,
    MilestoneDetailResponseWrapper,
    MilestoneDependencyCreateResponseWrapper,
    MilestoneStatsResponse,
    MilestoneStatsWrapper,
)

# Analytics schemas
from .analytics import (
    TaskSummaryResponse,
    TimeSummaryResponse,
    TeamPerformanceResponse,
    MilestoneProgressResponse,
    ProjectProgressResponse,
    ProjectAnalyticsResponse,
    TimelineEventResponse,
    ProjectTimelineResponse,
    ProjectProgressWrapper,
    ProjectTimelineWrapper,
    AnalyticsFilterRequest,
    DashboardSummaryResponse,
    DashboardSummaryWrapper,
)

# Task schemas
from .task import (
    TaskCreateRequest,
    TaskUpdateRequest,
    TaskDependencyRequest,
    TaskResponse,
    TaskDetailResponse,
    TaskDependencyResponse,
    TaskAssigneeResponse,
    TaskProjectResponse,
    TaskDependencySummaryResponse,
    TaskTimeEntryResponse,
    TaskCommentResponse,
    TaskListResponse,
    TaskCreateResponseWrapper,
    TaskUpdateResponseWrapper,
    TaskDeleteResponseWrapper,
    TaskDetailResponseWrapper,
    TaskDependencyCreateResponseWrapper,
    TaskStatsResponse,
    TaskStatsWrapper,
)

__all__ = [
    # Authentication schemas
    "UserLoginRequest",
    "UserRegisterRequest", 
    "TokenRefreshRequest",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "ChangePasswordRequest",
    "EmailVerificationRequest",
    "ResendVerificationRequest",
    "UserResponse",
    "TokenResponse",
    "TokenRefreshResponse",
    "LoginResponse",
    "RegisterResponse",
    "RefreshResponse",
    "LogoutResponse",
    "ForgotPasswordResponse",
    "ResetPasswordResponse",
    "ChangePasswordResponse",
    "EmailVerificationResponse",
    "ResendVerificationResponse",
    "SessionsResponse",
    "RevokeSessionResponse",
    "SessionInfo",
    "ErrorResponse",
    # User schemas
    "UserCreateRequest",
    "UserUpdateRequest",
    "UserSkillRequest",
    "UserQueryParams",
    "UserDetailResponse",
    "UserListResponse",
    "UserSkillResponse",
    "PaginationInfo",
    "UserListResponseWrapper",
    "UserResponseWrapper",
    "UserCreateResponseWrapper",
    "UserUpdateResponseWrapper",
    "UserDeleteResponseWrapper",
    "UserSkillResponseWrapper",
    # Profile schemas
    "ProfileUpdateRequest",
    "ProfileResponse",
    "AvatarUploadResponse",
    "ProfileUpdateResponse",
    "ProfileResponseWrapper",
    # Skills schemas
    "SkillRequest",
    "SkillResponse",
    "SkillListResponse",
    "SkillCreateResponseWrapper",
    "SkillUpdateResponseWrapper",
    "SkillDeleteResponseWrapper",
    # Project schemas
    "ProjectCreateRequest",
    "ProjectUpdateRequest",
    "ProjectQueryParams",
    "TeamMemberRequest",
    "ProjectResponse",
    "ProjectListResponse",
    "TeamMemberResponse",
    "ProjectCreateResponseWrapper",
    "ProjectUpdateResponseWrapper",
    "ProjectDeleteResponseWrapper",
    "ProjectListResponseWrapper",
    "ProjectResponseWrapper",
    # Team schemas
    "TeamMemberRoleUpdateRequest",
    "TeamMemberDetailResponse",
    "TeamListResponse",
    "TeamMemberUpdateResponse",
    "TeamMemberAddResponse",
    "TeamMemberRemoveResponse",
    "TeamStatsResponse",
    "TeamStatsWrapper",
    # Milestone schemas
    "MilestoneCreateRequest",
    "MilestoneUpdateRequest",
    "MilestoneDependencyRequest",
    "MilestoneResponse",
    "MilestoneDetailResponse",
    "MilestoneDependencyResponse",
    "MilestoneListResponse",
    "MilestoneCreateResponseWrapper",
    "MilestoneUpdateResponseWrapper",
    "MilestoneDeleteResponseWrapper",
    "MilestoneDetailResponseWrapper",
    "MilestoneDependencyCreateResponseWrapper",
    "MilestoneStatsResponse",
    "MilestoneStatsWrapper",
    # Analytics schemas
    "TaskSummaryResponse",
    "TimeSummaryResponse",
    "TeamPerformanceResponse",
    "MilestoneProgressResponse",
    "ProjectProgressResponse",
    "ProjectAnalyticsResponse",
    "TimelineEventResponse",
    "ProjectTimelineResponse",
    "ProjectProgressWrapper",
    "ProjectTimelineWrapper",
    "AnalyticsFilterRequest",
    "DashboardSummaryResponse",
    "DashboardSummaryWrapper",
    # Task schemas
    "TaskCreateRequest",
    "TaskUpdateRequest",
    "TaskDependencyRequest",
    "TaskResponse",
    "TaskDetailResponse",
    "TaskDependencyResponse",
    "TaskAssigneeResponse",
    "TaskProjectResponse",
    "TaskDependencySummaryResponse",
    "TaskTimeEntryResponse",
    "TaskCommentResponse",
    "TaskListResponse",
    "TaskCreateResponseWrapper",
    "TaskUpdateResponseWrapper",
    "TaskDeleteResponseWrapper",
    "TaskDetailResponseWrapper",
    "TaskDependencyCreateResponseWrapper",
    "TaskStatsResponse",
    "TaskStatsWrapper",
]
